name: Update Goldens
on: workflow_dispatch
jobs:
  update_goldens:
    name: Update Golden Files
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup app_secrets.dart
        env:
          APP_SECRETS: ${{ secrets.APP_SECRETS }}
          APP_SECRETS_PATH: lib/secrets/app_secrets.dart
        run: echo -n $APP_SECRETS | base64 --decode > $APP_SECRETS_PATH

      - name: Get Dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build

      - name: Generate Goldens
        run: flutter test --tags=golden test/presentation/goldens --update-goldens

      - name: Configure Git
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"

      - name: Commit changes
        run: git add test/presentation/goldens && git commit -m "Updated golden files"

      - uses: nelonoel/branch-name@v1.0.1

      - name: Push changes
        run: git push origin ${BRANCH_NAME}

